const STORAGE_KEY = 'assigntrack-state-v1';
const SESSION_KEY = 'assigntrack-session';
const initialState = {
  user: { id: 'student-001', role: 'student', name: 'Shahbaz Anjum', studentId: 'IT2024-018', email: 'shahbazanjum8888@gmail.com', course: 'BSc Information Technology', department: 'Computer Science', year: 'Final Year', semester: 'Semester 6', division: 'B' },
  subjects: [
    { id: 'web', name: 'Web Development', code: 'IT603', faculty: 'Prof. Maya Shah', assignments: 2 },
    { id: 'db', name: 'Database Management', code: 'IT604', faculty: 'Dr. Neel Joshi', assignments: 1 },
    { id: 'python', name: 'Python Programming', code: 'IT605', faculty: 'Prof. Riya Nair', assignments: 1 },
    { id: 'cloud', name: 'Cloud Computing', code: 'IT606', faculty: 'Prof. Omar Khan', assignments: 1 }
  ],
  assignments: [
    { id: 'a1', title: 'Web Development Assignment 01', subject: 'Web Development', subjectId: 'web', faculty: 'Prof. Maya Shah', assigned: '2026-08-22', due: '2026-09-10', description: 'Build a responsive student portal using semantic HTML, CSS and JavaScript.', instructions: 'Submit a zipped project folder with a short README explaining your design decisions.', maxMarks: 20, fileTypes: 'ZIP, PDF', maxSize: '10 MB', attempts: 2, status: 'pending', submission: null, resources: ['assignment-brief.pdf'] },
    { id: 'a2', title: 'Database Schema Design', subject: 'Database Management', subjectId: 'db', faculty: 'Dr. Neel Joshi', assigned: '2026-08-15', due: '2026-09-06', description: 'Design a normalized schema for an online learning platform.', instructions: 'Include an ER diagram and SQL DDL statements.', maxMarks: 25, fileTypes: 'PDF, DOCX', maxSize: '8 MB', attempts: 1, status: 'graded', submission: { date: '2026-08-29T11:20:00', fileName: 'aarav-db-schema.pdf', size: 482000, attempt: 1, marks: 22, feedback: 'Strong normalization choices. Add clearer relationship cardinalities.', gradedDate: '2026-09-02' }, resources: ['schema-reference.pdf'] },
    { id: 'a3', title: 'Python Data Analysis', subject: 'Python Programming', subjectId: 'python', faculty: 'Prof. Riya Nair', assigned: '2026-08-30', due: '2026-09-15', description: 'Analyze the supplied dataset and communicate three useful insights.', instructions: 'Submit your notebook and a PDF summary of your findings.', maxMarks: 30, fileTypes: 'IPYNB, PDF', maxSize: '15 MB', attempts: 2, status: 'submitted', submission: { date: '2026-09-01T16:10:00', fileName: 'aarav-analysis.ipynb', size: 920000, attempt: 1, marks: null, feedback: '', gradedDate: null }, resources: ['sales-data.csv'] },
    { id: 'a4', title: 'Cloud Architecture Notes', subject: 'Cloud Computing', subjectId: 'cloud', faculty: 'Prof. Omar Khan', assigned: '2026-09-01', due: '2026-09-20', description: 'Compare two deployment patterns for a small e-commerce service.', instructions: 'Use diagrams and cite at least three technical sources.', maxMarks: 20, fileTypes: 'PDF, DOCX', maxSize: '5 MB', attempts: 1, status: 'pending', submission: null, resources: [] },
    { id: 'a5', title: 'Web Accessibility Audit', subject: 'Web Development', subjectId: 'web', faculty: 'Prof. Maya Shah', assigned: '2026-08-05', due: '2026-08-28', description: 'Audit an existing website against WCAG principles.', instructions: 'Document findings with screenshots and remediation advice.', maxMarks: 15, fileTypes: 'PDF', maxSize: '5 MB', attempts: 1, status: 'overdue', submission: null, resources: [] }
  ],
  notifications: [
    { id: 'n1', type: 'New assignment', message: 'Cloud Architecture Notes was added to your assignments.', date: '2026-09-01T09:00:00', read: false },
    { id: 'n2', type: 'Assignment graded', message: 'Database Schema Design has been graded. View your feedback.', date: '2026-09-02T13:15:00', read: false },
    { id: 'n3', type: 'Deadline approaching', message: 'Database Schema Design is due in 3 days.', date: '2026-09-03T08:30:00', read: true }
  ],
  activity: [
    { icon: '✓', text: 'Database Schema Design was graded', date: '2026-09-02T13:15:00' },
    { icon: '↑', text: 'Submitted Python Data Analysis', date: '2026-09-01T16:10:00' },
    { icon: '+', text: 'New Cloud Architecture Notes received', date: '2026-09-01T09:00:00' }
  ]
};
let state = loadState();
let currentPage = location.hash.slice(1) || 'dashboard';
let selectedAssignment = null;

function loadState() { try { return JSON.parse(localStorage.getItem(STORAGE_KEY)) || structuredClone(initialState); } catch { return structuredClone(initialState); } }
function saveState() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function isLoggedIn() { return sessionStorage.getItem(SESSION_KEY) === state.user.id; }
function escapeHtml(value) { return String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char])); }
function initials(name) { return name.split(' ').map(part => part[0]).slice(0, 2).join('').toUpperCase(); }
function formatDate(value) { return new Date(`${value}T12:00:00`).toLocaleDateString(undefined, { day: 'numeric', month: 'short', year: 'numeric' }); }
function formatDateTime(value) { return new Date(value).toLocaleDateString(undefined, { day: 'numeric', month: 'short', year: 'numeric' }); }
function daysUntil(value) { return Math.ceil((new Date(`${value}T23:59:59`) - new Date()) / 86400000); }
function statusOf(assignment) { if (assignment.submission?.marks !== null && assignment.submission?.marks !== undefined) return 'graded'; if (assignment.submission) return 'submitted'; if (new Date(`${assignment.due}T23:59:59`) < new Date()) return 'overdue'; return assignment.status === 'resubmission' ? 'resubmission' : 'pending'; }
function statusBadge(status) { const labels = { pending: 'Pending', submitted: 'Submitted', graded: 'Graded', overdue: 'Overdue', resubmission: 'Resubmission Required' }; return `<span class="badge ${status}">${labels[status]}</span>`; }
function toast(message) { const region = document.getElementById('toast-region'); const item = document.createElement('div'); item.className = 'toast'; item.textContent = message; region.appendChild(item); setTimeout(() => item.remove(), 3500); }
function nav() { return [{ id: 'dashboard', icon: '⌂', label: 'Dashboard' }, { id: 'assignments', icon: '▣', label: 'My Assignments' }, { id: 'subjects', icon: '◈', label: 'Subjects' }, { id: 'submissions', icon: '↑', label: 'Submissions' }, { id: 'grades', icon: '★', label: 'Grades & Feedback' }, { id: 'calendar', icon: '□', label: 'Calendar' }, { id: 'notifications', icon: '●', label: 'Notifications' }, { id: 'profile', icon: '○', label: 'My Profile' }, { id: 'settings', icon: '⚙', label: 'Settings' }]; }
function renderLogin() { document.getElementById('app').innerHTML = `<main class="login-page"><section class="login-copy"><div class="brand"><span class="brand-mark">A</span> AssignTrack</div><div class="eyebrow">Student workspace</div><h1>Make every deadline count.</h1><p>A clear place to track assignments, submit work, and turn feedback into your next strong result.</p></section><form class="login-card" id="login-form"><h2>Welcome back</h2><p>Sign in to your student dashboard.</p><div class="field"><label for="email">College email</label><input class="input" id="email" type="email" value="aarav.mehta@example.edu" required></div><div class="field" style="margin-top:15px"><label for="password">Password</label><input class="input" id="password" type="password" value="student123" required></div><button class="button primary" style="margin-top:20px;width:100%">Sign in to AssignTrack</button><div class="demo-note">Demo access is prefilled. Your changes persist in this browser.</div></form></main>`; document.getElementById('login-form').addEventListener('submit', event => { event.preventDefault(); sessionStorage.setItem(SESSION_KEY, state.user.id); location.hash = 'dashboard'; render(); }); }
function renderShell(content) { const unread = state.notifications.filter(note => !note.read).length; document.getElementById('app').innerHTML = `<div class="app-shell"><aside class="sidebar" id="sidebar"><div class="brand"><span class="brand-mark">A</span> AssignTrack</div><div class="nav-label">Workspace</div><nav class="nav-list" aria-label="Student navigation">${nav().map(item => `<a class="nav-link ${currentPage === item.id ? 'active' : ''}" href="#${item.id}"><span class="nav-icon">${item.icon}</span>${item.label}${item.id === 'notifications' && unread ? `<span class="badge overdue" style="margin-left:auto;padding:3px 6px">${unread}</span>` : ''}</a>`).join('')}</nav><div class="sidebar-footer">Student workspace<br><strong>${escapeHtml(state.user.course)}</strong></div></aside><main class="main"><header class="topbar"><button class="menu-button" id="menu-button" aria-label="Open navigation">☰</button><div class="topbar-actions"><a class="icon-button" href="#notifications" aria-label="Notifications">♢${unread ? '<span class="notification-dot"></span>' : ''}</a><a class="profile-chip" href="#profile"><span class="avatar">${initials(state.user.name)}</span><div><strong>${escapeHtml(state.user.name)}</strong><small>Student</small></div></a></div></header>${content}</main></div>`; document.getElementById('menu-button').addEventListener('click', () => document.getElementById('sidebar').classList.toggle('open')); document.querySelectorAll('.nav-link').forEach(link => link.addEventListener('click', () => document.getElementById('sidebar').classList.remove('open'))); }
function pageIntro(eyebrow, title, text, action = '') { return `<div class="page-intro"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${text}</p></div>${action}</div>`; }
function renderDashboard() { const assignments = state.assignments; const statuses = assignments.map(statusOf); const graded = assignments.filter(a => statusOf(a) === 'graded'); const average = graded.length ? Math.round(graded.reduce((sum, a) => sum + a.submission.marks / a.maxMarks * 100, 0) / graded.length) : 0; const upcoming = assignments.filter(a => ['pending', 'resubmission'].includes(statusOf(a))).sort((a, b) => a.due.localeCompare(b.due)).slice(0, 3); const activity = state.activity.slice(0, 4); return pageIntro('Thursday, 3 September 2026', `Good morning, ${escapeHtml(state.user.name.split(' ')[0])}.`, 'Here is your assignment overview.', '<a class="button primary" href="#assignments">View assignments</a>') + `<section class="summary-grid"><div class="stat-card"><div class="stat-label">Total assignments</div><div class="stat-number">${assignments.length}</div><div class="stat-note">This semester</div></div><div class="stat-card"><div class="stat-label">Pending</div><div class="stat-number">${statuses.filter(s => ['pending', 'resubmission'].includes(s)).length}</div><div class="stat-note">Keep moving</div></div><div class="stat-card"><div class="stat-label">Submitted</div><div class="stat-number">${statuses.filter(s => s === 'submitted').length}</div><div class="stat-note">Awaiting review</div></div><div class="stat-card"><div class="stat-label">Due soon</div><div class="stat-number">${assignments.filter(a => daysUntil(a.due) >= 0 && daysUntil(a.due) <= 7 && statusOf(a) !== 'graded').length}</div><div class="stat-note">Next 7 days</div></div><div class="stat-card"><div class="stat-label">Graded</div><div class="stat-number">${graded.length}</div><div class="stat-note">Feedback available</div></div><div class="stat-card"><div class="stat-label">Average score</div><div class="stat-number">${average}%</div><div class="stat-note">Across graded work</div></div></section><div class="content-grid"><section class="panel"><div class="panel-header"><h2>Upcoming work</h2><a class="link-button" href="#assignments">See all</a></div>${upcoming.length ? upcoming.map(a => `<div class="assignment-row"><div><h3>${escapeHtml(a.title)}</h3><p>${escapeHtml(a.subject)} · Due ${formatDate(a.due)}</p></div>${statusBadge(statusOf(a))}<button class="button secondary" data-view="${a.id}">Open</button></div>`).join('') : '<div class="empty">No assignments assigned yet.</div>'}</section><section class="panel"><div class="panel-header"><h2>Recent activity</h2><a class="link-button" href="#notifications">All updates</a></div><div class="activity-list">${activity.length ? activity.map(item => `<div class="activity"><span class="activity-mark">${item.icon}</span><div><p>${escapeHtml(item.text)}</p><time>${formatDateTime(item.date)}</time></div></div>`).join('') : '<div class="empty">No activity yet.</div>'}</div></section></div>`; }
function assignmentTable(list) { return list.length ? `<div class="table-wrap"><table class="data-table"><thead><tr><th>Assignment</th><th>Due date</th><th>Status</th><th>Marks</th><th></th></tr></thead><tbody>${list.map(a => { const status = statusOf(a); return `<tr><td><strong>${escapeHtml(a.title)}</strong><small>${escapeHtml(a.subject)} · ${escapeHtml(a.faculty)}</small></td><td>${formatDate(a.due)}</td><td>${statusBadge(status)}</td><td>${a.submission?.marks != null ? `${a.submission.marks} / ${a.maxMarks}` : '—'}</td><td><button class="button secondary" data-view="${a.id}">View</button></td></tr>`; }).join('')}</tbody></table></div>` : '<div class="empty">No assignments match those filters.</div>'; }
function renderAssignments() { return pageIntro('Your workload', 'My assignments', 'Search, sort, and stay ahead of every submission.') + `<section class="panel"><div class="filter-bar"><input class="input search" id="assignment-search" placeholder="Search title, subject, or faculty" aria-label="Search assignments"><select class="select" id="status-filter" aria-label="Filter by status"><option value="all">All statuses</option><option value="pending">Pending</option><option value="submitted">Submitted</option><option value="graded">Graded</option><option value="overdue">Overdue</option><option value="resubmission">Resubmission required</option></select><select class="select" id="subject-filter" aria-label="Filter by subject"><option value="all">All subjects</option>${state.subjects.map(s => `<option value="${s.name}">${s.name}</option>`).join('')}</select><select class="select" id="sort-filter" aria-label="Sort assignments"><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="deadline">Deadline</option><option value="subject">Subject</option><option value="marks">Marks</option></select></div><div id="assignment-results">${assignmentTable(state.assignments)}</div></section>`; }
function filteredAssignments() { const query = document.getElementById('assignment-search').value.toLowerCase(); const status = document.getElementById('status-filter').value; const subject = document.getElementById('subject-filter').value; const sort = document.getElementById('sort-filter').value; const list = state.assignments.filter(a => (!query || `${a.title} ${a.subject} ${a.faculty}`.toLowerCase().includes(query)) && (status === 'all' || statusOf(a) === status) && (subject === 'all' || a.subject === subject)); return list.sort((a, b) => sort === 'oldest' ? a.assigned.localeCompare(b.assigned) : sort === 'deadline' ? a.due.localeCompare(b.due) : sort === 'subject' ? a.subject.localeCompare(b.subject) : sort === 'marks' ? (b.submission?.marks ?? -1) - (a.submission?.marks ?? -1) : b.assigned.localeCompare(a.assigned)); }
function renderSubjects() { return pageIntro('Your curriculum', 'My subjects', 'Your enrolled subjects and the work connected to each one.') + `<section class="subject-grid">${state.subjects.length ? state.subjects.map(subject => `<article class="subject-card"><div class="eyebrow">${subject.code}</div><h2>${escapeHtml(subject.name)}</h2><p>${escapeHtml(subject.faculty)}</p><div class="subject-count">${state.assignments.filter(a => a.subjectId === subject.id).length} assignments</div><div class="actions"><button class="button secondary" data-subject="${subject.name}">View assignments</button></div></article>`).join('') : '<div class="empty">No enrolled subjects found.</div>'}</section>`; }
function renderSubmissions() { const submitted = state.assignments.filter(a => a.submission); return pageIntro('Your work', 'Submission history', 'A record of every file you have sent to faculty.') + `<section class="panel">${submitted.length ? `<div class="table-wrap"><table class="data-table"><thead><tr><th>Assignment</th><th>Submitted</th><th>File</th><th>Attempt</th><th>Status</th><th>Marks</th></tr></thead><tbody>${submitted.map(a => `<tr><td><strong>${escapeHtml(a.title)}</strong><small>${escapeHtml(a.subject)}</small></td><td>${formatDateTime(a.submission.date)}</td><td>${escapeHtml(a.submission.fileName)}</td><td>${a.submission.attempt} / ${a.attempts}</td><td>${statusBadge(statusOf(a))}</td><td>${a.submission.marks != null ? `${a.submission.marks} / ${a.maxMarks}` : 'Awaiting review'}</td></tr>`).join('')}</tbody></table></div>` : '<div class="empty">You have not submitted any assignments yet.</div>'}</section>`; }
function renderGrades() { const graded = state.assignments.filter(a => statusOf(a) === 'graded'); const average = graded.length ? Math.round(graded.reduce((sum, a) => sum + a.submission.marks / a.maxMarks * 100, 0) / graded.length) : 0; return pageIntro('Your results', 'Grades & feedback', 'Use faculty feedback to make the next submission even stronger.') + `<div class="content-grid"><section class="panel grade-highlight"><div class="eyebrow" style="color:var(--yellow)">Overall average</div><div class="performance-number">${average}%</div><p class="muted-light">${graded.length} graded assignment${graded.length === 1 ? '' : 's'} · ${state.assignments.filter(a => statusOf(a) === 'pending').length} pending</p><div class="progress"><span style="width:${average}%"></span></div></section><section class="panel"><div class="panel-header"><h2>Performance overview</h2></div><div class="detail-grid"><div class="detail-item"><label>Submitted</label><p>${state.assignments.filter(a => ['submitted', 'graded'].includes(statusOf(a))).length}</p></div><div class="detail-item"><label>Overdue</label><p>${state.assignments.filter(a => statusOf(a) === 'overdue').length}</p></div></div></section></div><section class="panel" style="margin-top:20px"><div class="panel-header"><h2>Evaluated assignments</h2></div>${graded.length ? `<div class="table-wrap"><table class="data-table"><thead><tr><th>Assignment</th><th>Faculty</th><th>Score</th><th>Percentage</th><th>Feedback</th></tr></thead><tbody>${graded.map(a => `<tr><td><strong>${escapeHtml(a.title)}</strong><small>${escapeHtml(a.subject)}</small></td><td>${escapeHtml(a.faculty)}</td><td>${a.submission.marks} / ${a.maxMarks}</td><td>${Math.round(a.submission.marks / a.maxMarks * 100)}%</td><td>${escapeHtml(a.submission.feedback || 'No written feedback')}</td></tr>`).join('')}</tbody></table></div>` : '<div class="empty">No graded assignments yet.</div>'}</section>`; }
function renderCalendar() { const month = 8; const year = 2026; const first = new Date(year, month, 1).getDay(); const total = new Date(year, month + 1, 0).getDate(); const days = []; for (let i = 0; i < first; i++) days.push('<div class="calendar-day muted"></div>'); for (let day = 1; day <= total; day++) { const date = `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`; const events = state.assignments.filter(a => a.due === date); days.push(`<div class="calendar-day ${date === '2026-09-03' ? 'today' : ''} ${events.length ? 'has-event' : ''}">${day}${events.map(a => `<span class="calendar-event" title="${escapeHtml(a.title)}">${escapeHtml(a.title)}</span>`).join('')}</div>`); } return pageIntro('Stay on track', 'Calendar', 'September 2026 deadlines at a glance.') + `<section class="panel"><div class="panel-header"><h2>September 2026</h2><span class="badge submitted">Today · 3 Sep</span></div><div class="calendar-grid">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d => `<div class="calendar-name">${d}</div>`).join('')}${days.join('')}</div></section>`; }
function renderNotifications() { return pageIntro('Stay informed', 'Notifications', 'Updates from your courses, submissions, and faculty.', `<button class="button secondary" id="mark-all">Mark all as read</button>`) + `<section class="panel">${state.notifications.length ? state.notifications.map(note => `<div class="notification-item ${note.read ? '' : 'unread'}"><span class="activity-mark">${note.read ? '✓' : '!'}</span><div><p><strong>${escapeHtml(note.type)}</strong> · ${escapeHtml(note.message)}</p><time>${formatDateTime(note.date)}</time></div>${!note.read ? `<button class="text-button" data-read="${note.id}">Mark read</button>` : ''}</div>`).join('') : '<div class="empty">You are all caught up.</div>'}</section>`; }
function renderProfile() { return pageIntro('Account', 'My profile', 'Keep your student details current for faculty and course records.') + `<div class="profile-layout"><section class="panel profile-card"><div class="avatar">${initials(state.user.name)}</div><h2>${escapeHtml(state.user.name)}</h2><p>${escapeHtml(state.user.studentId)}<br>${escapeHtml(state.user.email)}</p><span class="badge submitted">Profile 90% complete</span></section><section class="panel"><form id="profile-form" class="form-grid"><div class="field"><label for="profile-name">Full name</label><input class="input" id="profile-name" value="${escapeHtml(state.user.name)}" required></div><div class="field"><label for="profile-email">Email</label><input class="input" id="profile-email" type="email" value="${escapeHtml(state.user.email)}" required></div><div class="field"><label>Student ID / Roll number</label><input class="input" value="${escapeHtml(state.user.studentId)}" disabled></div><div class="field"><label>Course / Degree</label><input class="input" value="${escapeHtml(state.user.course)}" disabled></div><div class="field"><label>Department</label><input class="input" value="${escapeHtml(state.user.department)}" disabled></div><div class="field"><label>Year</label><input class="input" value="${escapeHtml(state.user.year)}" disabled></div><div class="field"><label>Semester</label><input class="input" value="${escapeHtml(state.user.semester)}" disabled></div><div class="field"><label>Division / Class</label><input class="input" value="${escapeHtml(state.user.division)}" disabled></div><div class="field full"><button class="button primary">Save profile changes</button></div></form></section></div>`; }
function renderSettings() { return pageIntro('Preferences', 'Settings', 'Choose how AssignTrack keeps you informed.') + `<section class="panel"><form id="settings-form"><div class="field"><label><input type="checkbox" checked> Email me when an assignment is graded</label></div><div class="field" style="margin-top:15px"><label><input type="checkbox" checked> Remind me 3 days before a deadline</label></div><div class="field" style="margin-top:15px"><label><input type="checkbox"> Send a weekly progress summary</label></div><div class="actions"><button class="button primary">Save preferences</button><button type="button" class="button danger" id="logout-button">Log out</button></div></form></section>`; }
function render() { if (!isLoggedIn()) return renderLogin(); const pages = { dashboard: renderDashboard, assignments: renderAssignments, subjects: renderSubjects, submissions: renderSubmissions, grades: renderGrades, calendar: renderCalendar, notifications: renderNotifications, profile: renderProfile, settings: renderSettings }; renderShell(pages[currentPage] ? pages[currentPage]() : renderDashboard()); bindPageEvents(); }
function showAssignment(id) { selectedAssignment = state.assignments.find(a => a.id === id); if (!selectedAssignment) return; const a = selectedAssignment; const status = statusOf(a); const resources = a.resources.length ? a.resources.map(file => `<div class="resource"><span>▧ ${escapeHtml(file)}</span><button class="text-button" data-download="${escapeHtml(file)}">Download</button></div>`).join('') : '<p class="detail-copy">No resources attached.</p>'; document.body.insertAdjacentHTML('beforeend', `<div class="modal-backdrop" id="assignment-modal"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button class="modal-close" id="close-modal" aria-label="Close">×</button><div class="eyebrow">${escapeHtml(a.subject)} · ${escapeHtml(a.faculty)}</div><h2 id="modal-title" style="margin:8px 35px 20px 0">${escapeHtml(a.title)}</h2><div class="detail-grid"><div class="detail-item"><label>Assigned</label><p>${formatDate(a.assigned)}</p></div><div class="detail-item"><label>Deadline</label><p>${formatDate(a.due)}</p></div><div class="detail-item"><label>Maximum marks</label><p>${a.maxMarks}</p></div><div class="detail-item"><label>Current status</label><p>${statusBadge(status)}</p></div><div class="detail-item"><label>Allowed files</label><p>${escapeHtml(a.fileTypes)}</p></div><div class="detail-item"><label>Maximum size</label><p>${escapeHtml(a.maxSize)} · ${a.attempts} attempt${a.attempts === 1 ? '' : 's'}</p></div></div><h3 style="margin-top:25px">Brief</h3><p class="detail-copy">${escapeHtml(a.description)}</p><h3>Instructions</h3><p class="detail-copy">${escapeHtml(a.instructions)}</p><h3>Resources</h3>${resources}<div class="actions">${status === 'graded' ? `<span class="badge graded">${a.submission.marks} / ${a.maxMarks}</span>` : `<button class="button primary" id="open-submit">${a.submission ? 'Submit again' : 'Submit assignment'}</button>`}<button class="button secondary" id="close-modal-action">Close</button></div></section></div>`); document.getElementById('close-modal').onclick = closeModal; document.getElementById('close-modal-action').onclick = closeModal; document.querySelector('[data-download]')?.addEventListener('click', () => toast('Resource downloads are available when connected to file storage.')); document.getElementById('open-submit')?.addEventListener('click', () => showSubmitForm(a)); }
function showSubmitForm(a) { const modal = document.getElementById('assignment-modal'); modal.querySelector('.modal').innerHTML = `<button class="modal-close" id="close-modal" aria-label="Close">×</button><div class="eyebrow">Submit assignment</div><h2 style="margin:8px 35px 20px 0">${escapeHtml(a.title)}</h2><form id="submit-form"><div class="field"><label for="submission-file">Choose file</label><input class="input" id="submission-file" type="file" required><small class="detail-copy">Accepted: ${escapeHtml(a.fileTypes)} · Max ${escapeHtml(a.maxSize)}</small></div><div class="field" style="margin-top:17px"><label for="submission-note">Optional note</label><textarea id="submission-note" placeholder="Add a note for your faculty member"></textarea></div><div class="actions"><button class="button primary">Submit assignment</button><button type="button" class="button secondary" id="cancel-submit">Cancel</button></div></form>`; document.getElementById('close-modal').onclick = closeModal; document.getElementById('cancel-submit').onclick = () => showAssignment(a.id); document.getElementById('submit-form').addEventListener('submit', event => { event.preventDefault(); const file = document.getElementById('submission-file').files[0]; const maxBytes = parseInt(a.maxSize) * 1024 * 1024; const extension = file?.name.split('.').pop().toUpperCase(); if (!file || !a.fileTypes.split(', ').includes(extension)) return toast(`Please choose an accepted file type: ${a.fileTypes}.`); if (file.size > maxBytes) return toast(`That file is larger than the ${a.maxSize} limit.`); if (a.submission && a.submission.attempt >= a.attempts) return toast('You have used all available attempts.'); if (new Date(`${a.due}T23:59:59`) < new Date()) return toast('The submission deadline has passed.'); a.submission = { date: new Date().toISOString(), fileName: file.name, size: file.size, attempt: (a.submission?.attempt || 0) + 1, marks: null, feedback: '', gradedDate: null }; a.status = 'submitted'; state.activity.unshift({ icon: '↑', text: `Submitted ${a.title}`, date: a.submission.date }); state.notifications.unshift({ id: `n-${Date.now()}`, type: 'Successful submission', message: `${a.title} was submitted successfully.`, date: a.submission.date, read: false }); saveState(); closeModal(); render(); toast('Assignment submitted successfully.'); }); }
function closeModal() { document.getElementById('assignment-modal')?.remove(); selectedAssignment = null; }
function bindPageEvents() { document.querySelectorAll('[data-view]').forEach(button => button.addEventListener('click', () => showAssignment(button.dataset.view))); if (currentPage === 'assignments') { ['assignment-search','status-filter','subject-filter','sort-filter'].forEach(id => document.getElementById(id).addEventListener('input', () => document.getElementById('assignment-results').innerHTML = assignmentTable(filteredAssignments()))); } document.querySelectorAll('[data-subject]').forEach(button => button.addEventListener('click', () => { location.hash = 'assignments'; setTimeout(() => { document.getElementById('subject-filter').value = button.dataset.subject; document.getElementById('assignment-results').innerHTML = assignmentTable(filteredAssignments()); }, 0); })); document.querySelectorAll('[data-read]').forEach(button => button.addEventListener('click', () => { const note = state.notifications.find(item => item.id === button.dataset.read); if (note) note.read = true; saveState(); render(); })); document.getElementById('mark-all')?.addEventListener('click', () => { state.notifications.forEach(note => note.read = true); saveState(); render(); toast('All notifications marked as read.'); }); document.getElementById('profile-form')?.addEventListener('submit', event => { event.preventDefault(); state.user.name = document.getElementById('profile-name').value.trim(); state.user.email = document.getElementById('profile-email').value.trim(); saveState(); render(); toast('Profile updated successfully.'); }); document.getElementById('settings-form')?.addEventListener('submit', event => { event.preventDefault(); toast('Preferences saved.'); }); document.getElementById('logout-button')?.addEventListener('click', () => { sessionStorage.removeItem(SESSION_KEY); location.hash = ''; render(); }); }
window.addEventListener('hashchange', () => { currentPage = location.hash.slice(1) || 'dashboard'; render(); });
async function hydrateState() { if (!isLoggedIn()) return; try { const response = await fetch('/api/student/dashboard', { credentials: 'same-origin' }); if (!response.ok) return; const serverState = await response.json(); state = { ...state, ...serverState }; render(); } catch { /* Static-file mode keeps the local fallback available. */ } }
document.addEventListener('submit', async event => {
  if (event.target.id === 'login-form') {
    event.preventDefault();
    event.stopPropagation();
    const form = event.target;
    fetch('/api/auth/login', { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: form.email.value, password: form.password.value }) }).then(async response => { if (!response.ok) return toast((await response.json()).error || 'Unable to sign in.'); sessionStorage.setItem(SESSION_KEY, state.user.id); location.hash = 'dashboard'; render(); hydrateState(); }).catch(() => toast('Unable to reach the AssignTrack server.'));
  }
}, true);
document.addEventListener('submit', async event => {
  if (event.target.id !== 'submit-form' || !selectedAssignment) return;
  event.preventDefault();
  event.stopPropagation();
  const file = document.getElementById('submission-file').files[0];
  if (!file) return toast('Please choose a file.');
  const data = await new Promise(resolve => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(',')[1]); reader.readAsDataURL(file); });
  const response = await fetch(`/api/student/assignments/${selectedAssignment.id}/submissions`, { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ fileName: file.name, size: file.size, data, note: document.getElementById('submission-note').value }) });
  const result = await response.json();
  if (!response.ok) return toast(result.error || 'Submission failed.');
  closeModal();
  await hydrateState();
  toast('Assignment submitted successfully.');
}, true);
document.addEventListener('submit', event => {
  if (event.target.id === 'profile-form') {
    fetch('/api/student/profile', { method: 'PATCH', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: event.target.querySelector('#profile-name').value, email: event.target.querySelector('#profile-email').value }) });
  }
});
document.addEventListener('click', event => {
  const readButton = event.target.closest('[data-read]');
  if (readButton) fetch(`/api/student/notifications/${readButton.dataset.read}/read`, { method: 'PATCH', credentials: 'same-origin' });
  if (event.target.id === 'mark-all') fetch('/api/student/notifications/read-all', { method: 'PATCH', credentials: 'same-origin' });
});
render();
hydrateState();
